<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('registration'));
    $form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form); ?>

<div class="form_element">
    <?php echo $this->formRow($form->get('login')); ?>
</div>
<div class="form_element">
    <?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form_element">
    <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form_element">
    <?php echo $this->formRow($form->get('captcha')); ?>
</div>

    <?php echo $this->formElement($form->get('csrfReg')); ?>
    <?php echo $this->formElement($form->get('submit')); ?>

<?php echo $this->form()->closeTag($this->form); ?>
