<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Service\Users'             => __DIR__ . '/src/User/Service/Users.php',
  'User\Entity\User'               => __DIR__ . '/src/User/Entity/User.php',
  'User\Repository\UserRepository' => __DIR__ . '/src/User/Repository/UserRepository.php',
  'User\Form\Login'                => __DIR__ . '/src/User/Form/Login.php',
  'User\Form\Registration'         => __DIR__ . '/src/User/Form/Registration.php',
  'User\Controller\AuthController' => __DIR__ . '/src/User/Controller/AuthController.php',
  'User\Controller\UserController' => __DIR__ . '/src/User/Controller/UserController.php',
  'User\Module'                    => __DIR__ . '/Module.php',
);
