<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Service\EntityManagerAwareInterface'    => __DIR__ . '/src/Application/Service/EntityManagerAwareInterface.php',
  'Application\Service\Traits\EntityManagerAwareTrait' => __DIR__ . '/src/Application/Service/Traits/EntityManagerAwareTrait.php',
  'Application\Controller\IndexController'             => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Module'                                 => __DIR__ . '/Module.php',
);
