<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'layout/layout'            => __DIR__ . '/view/layout/layout.phtml',
    'error/index'              => __DIR__ . '/view/error/index.phtml',
    'error/404'                => __DIR__ . '/view/error/404.phtml',
    'application/index/index'  => __DIR__ . '/view/application/index/index.phtml',
    'application/index/search' => __DIR__ . '/view/application/index/search.phtml',
);
